export const HOUSE_LIST_REQUEST = "HOUSE_LIST_REQUEST";
export const HOUSE_LIST_SUCCESS = "HOUSE_LIST_SUCCESS";
export const HOUSE_LIST_FAIL = "HOUSE_LIST_FAIL";

export const HOUSE_DETAILS_REQUEST = "HOUSE_DETAILS_REQUEST";
export const HOUSE_DETAILS_SUCCESS = "HOUSE_DETAILS_SUCCESS";
export const HOUSE_DETAILS_FAIL = "HOUSE_DETAILS_FAIL";

export const HOUSE_CREATE_REVIEW_REQUEST = "HOUSE_CREATE_REVIEW_REQUEST";
export const HOUSE_CREATE_REVIEW_SUCCESS = "HOUSE_CREATE_REVIEW_SUCCESS";
export const HOUSE_CREATE_REVIEW_FAIL = "HOUSE_CREATE_REVIEW_FAIL";
export const HOUSE_CREATE_REVIEW_RESET = "HOUSE_CREATE_REVIEW_RESET";
